discover_devices:
  description: Discover IoT Explorer devices on the network
  fields:
    entry_id:
      description: The config entry ID
      example: 1234567890abcdef1234567890abcdef
      required: true