scan:
  description: "Force a scan for new IoT Explorer devices"
  fields:
    full_scan:
      description: "Perform a full network scan (slower but more thorough)"
      required: false
      example: true
      default: false
      selector:
        boolean: